### ISSUE TITLE
InternetDate.Parse fails verification under .NET Framework 2.0

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/Jayrock#1]
## What steps will reproduce the problem?
1. Run `PEVerify.exe` from .NET Framework 2.0 SDK on `Jayrock.Json.dll`
## What is the expected output? What do you see instead?

Expected all classes and method to pass verification. Instead, verification fails on InternetDate.Parse as shown below:

```
Microsoft (R) .NET Framework PE Verifier.  Version  2.0.50727.42
Copyright (c) Microsoft Corporation.  All rights reserved.

[IL]: Error: [C:\Jayrock\bin\Debug\Jayrock.Json.dll : 
Jayrock.InternetDate::Parse][offset 0x00000024] The 'this' parameter to the call must be the calling method's 'this' parameter.
[IL]: Error: [C:\Jayrock\bin\Debug\Jayrock.Json.dll : 
Jayrock.InternetDate::Parse][offset 0x00000137] The 'this' parameter to the call must be the calling method's 'this' parameter.
2 Errors Verifying \Jayrock\bin\Debug\Jayrock.Json.dll
```
## Additional information:

This issue was originally reported by Phil Haack (@haacked) in the following thread on the discussion group: [VerificationException thrown on first request](http://groups.google.com/group/jayrock/t/2369463aa15b23a)

Version of `Jayrock.Json.dll` tested:
- File Version: 0.9.10312.2155
- Product Version: 0.9.8316.0

---

Originally reported on Google Code with ID 1

Reported by @atifaziz on 2008-11-10 10:00:48

**Comment by Haacked** [comment]
:+1: Only seven years later! :stuck_out_tongue:

**Comment by atifaziz** [comment]
@Haacked Dude, this issue was addressed on the same day (Nov 10, 2008) you reported it. It's just on GitHub 7 years later now that [Google Code is shutting down](http://google-opensource.blogspot.ch/2015/03/farewell-to-google-code.html).

**Comment by Haacked** [comment]
OH! Heh heh. Welcome to GitHub!!!
